__use_yte__: true

max-in-memory-rows: 5000

name: Diffexp vs DMRs
datasets:
  diffexp_vs_dmrs:
    path: ?input.comp
    separator: "\t"
default-view: diffexp_vs_dmrs
views:
  diffexp_vs_dmrs:
    dataset: diffexp_vs_dmrs
    desc: "To prioritize the most extreme cases toward the top-left or bottom-right, we sort values by the product of the DMR and differential expression scores. This ensures that strong effects in both dimensions are ranked highest."
    render-table:
      columns:
        qval_diffexp:
          spell:
            url: v1.5.1/stats/p-value
            with:
              significance_threshold: 0.05
        qval_dmr:
          spell:
            url: v1.5.1/stats/p-value
            with:
              significance_threshold: 0.05
        mean_methylation_difference:
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -1
                - 0
                - 1 
        diffexp:
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -5
                - 0
                - 5
        diffexp_se:
          plot:
            heatmap:
              scale: linear
              range:
                - "white"
                - "#6baed6"
              domain:
                - 0
                - 2
        germ_layer:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        ext_gene:
          display-mode: normal
          link-to-url: 
            geneontology: 
              url: https://www.genecards.org/cgi-bin/carddisp.pl?gene={ext_gene}
        
        ens_gene:
          display-mode: normal
          link-to-url: 
            geneontology: 
              url: https://useast.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g={ens_gene}
        pval_diffexp:
          display-mode: hidden
        pval_dmr:
          display-mode: hidden