__use_yte__: true

max-in-memory-rows: 5000

name: Diffexp vs DMRs
datasets:
  diffexp_vs_dmrs:
    path: ?input.comp
    separator: "\t"
default-view: diffexp_vs_dmrs
views:
  diffexp_vs_dmrs:
    dataset: diffexp_vs_dmrs
    desc: ?f"Describe this table in detail."
    render-table:
      columns:
        qval_diffexp:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.5
        qval_dmr:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.5
        mean_methylation_difference:
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -1
                - 0
                - 1 
        diffexp:
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -5
                - 0
                - 5
        diffexp_se:
          plot:
            heatmap:
              scale: linear
              range:
                - "white"
                - "#6baed6"
              domain:
                - 0
                - 2
        germ_layer:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20

        