__use_yte__: true


name: Diffexp vs DMRs
datasets:
  data_with_tfs:
    path: ?input.with_tfs
    separator: "\t"
    links:
      data_with_tfs:
        column: row_id
        table-row: diffexp_vs_dmrs_table_with_tfs/row_id
  data_focus_tfs:
    path: ?input.focus_tfs
    separator: "\t"
default-view: diffexp_vs_dmrs_plot_with_tfs
views:


  diffexp_vs_dmrs_table_with_tfs:
    dataset: data_with_tfs
    desc: ?f"Table with DMR values and DiffExp per gene and germ layer. The column ext gene shows all investigated genes. If a gene is influenced by transcription factors the column 'is tf target' will be true. You can find the  according transcription factors in the column tfs. To adjust the DMR of a gene by its transcription factors we sum over all DMRs of the single transcription factors. Sometimes for one gene we find multiple DMRs, in this case we build the mean over all DMRs for this transcription factor. Right now we do not change the qvals and pvals of a gene influenced by transcription factors."
    render-table:
      columns:
        row_id:
          display-mode: hidden
        is_tf_target:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        qval_diffexp:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.5
        qval_dmr:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.5
        mean_methylation_difference_tf_adjusted:
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -1
                - 0
                - 1 
        diffexp:
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -5
                - 0
                - 5
        diffexp_se:
          plot:
            heatmap:
              scale: linear
              range:
                - "white"
                - "#6baed6"
              domain:
                - 0
                - 2
        germ_layer:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        ext_gene:
          display-mode: normal
          link-to-url: 
            geneontology: 
              url: https://www.genecards.org/cgi-bin/carddisp.pl?gene={ext_gene}
        
        ens_gene:
          display-mode: normal
          link-to-url: 
            geneontology: 
              url: https://useast.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g={ens_gene}
        pval_diffexp:
          display-mode: hidden
        pval_dmr:
          display-mode: hidden


  diffexp_vs_dmrs_plot_with_tfs:
    dataset: data_with_tfs
    desc: |
      ?f"Scatter plot with DMR values and DiffExp per gene and germ_layer. To adjust the DMR of a gene by its transcription factors we sum over all DMRs of the single transcription factors. Sometimes for one gene we find multiple DMRs, in this case we build the mean over all DMRs for this transcription factor. Right now we do not change the qvals and pvals of a gene influenced by transcription factors. We show 'qval combined' (the maximum of the qvalues of the DMR and DiffExp analysis) as opacity of each data point. You can click on the Germ Layer legend to filter on specific germ layers. Furthermore you can click on a data point to see its details in a table."
    render-plot:
      spec: |
        {
          "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
          "config": {"view": {"continuousWidth": 500, "continuousHeight": 500}},
          "mark": {"type": "point", "filled": true},
          "encoding": {
            "color": {
              "condition": {
                "param": "Germ Layer",
                "field": "germ_layer",
                "scale": {"scheme": "category10"},
                "title": "Germ Layer",
                "type": "nominal"
              },
              "value": "lightgray"
            },
            "opacity": {
              "field": "qval_combined",
              "scale": {"range": [1, 0.1]},
              "title": "max(qval1, qval2)",
              "type": "quantitative"
            },
            "size": {
              "field": "qval_combined",
              "scale": {"range": [30, 1]},
              "title": "max(qval1, qval2)",
              "type": "quantitative"
            },
            "tooltip": [
              {"field": "ext_gene", "type": "nominal"},
              {"field": "ranked_meth_diffexp", "type": "quantitative"},
            ],
            "x": {"field": "diffexp", "type": "quantitative"},
            "y": {"field": "mean_methylation_difference_tf_adjusted", "type": "quantitative"},
            "href": {"field": "data_with_tfs"},
          },
          "params": [
            {
              "name": "Germ Layer",
              "select": {"type": "point", "fields": ["germ_layer"]},
              "bind": "legend"
            }
          ],          
        }



  tfs_only:
    dataset: data_focus_tfs
    desc: ?f"Scatter plot with DMR values and DiffExp per transcription factor and germ_layer. We show only transcription factors with target genes included in our analysis. We show 'qval combined' (the maximum of the qvalues of the DMR and DiffExp analysis) as opacity of each data point. You can click on the Germ Layer legend to filter on specific germ layers."
    render-plot:
      spec: |
        {
          "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
          "config": {"view": {"continuousWidth": 500, "continuousHeight": 500}},
          "mark": {"type": "point", "filled": true},
          "encoding": {
            "color": {
              "condition": {
                "param": "Germ Layer",
                "field": "germ_layer",
                "scale": {"scheme": "category10"},
                "title": "Germ Layer",
                "type": "nominal"
              },
              "value": "lightgray"
            },
            "opacity": {
              "field": "qval_combined",
              "scale": {"range": [1, 0.1]},
              "title": "max(qval1, qval2)",
              "type": "quantitative"
            },
            "size": {
              "field": "qval_combined",
              "scale": {"range": [30, 1]},
              "title": "max(qval1, qval2)",
              "type": "quantitative"
            },
            "tooltip": [
              {"field": "tfs", "type": "nominal"},
              {"field": "diffexp", "type": "quantitative"},
              {"field": "mean_methylation_difference", "type": "quantitative"},
              {"field": "qval_combined", "type": "quantitative"},
              {"field": "qval_diffexp", "type": "quantitative"},
              {"field": "qval_dmr", "type": "quantitative"}
            ],
            "x": {"field": "diffexp", "type": "quantitative"},
            "y": {"field": "mean_methylation_difference", "type": "quantitative"}
          },
          "params": [
            {
              "name": "Germ Layer",
              "select": {"type": "point", "fields": ["germ_layer"]},
              "bind": "legend"
            }
          ],       
        }
      
