__use_yte__: true

max-in-memory-rows: 5000

name: Gene set enrichment on genes differentially expressed and associated to DMRs
datasets:
  diffexp_vs_dmrs:
    path: ?input.comp
    separator: "\t"
default-view: diffexp_vs_dmrs
views:
  diffexp_vs_dmrs:
    dataset: diffexp_vs_dmrs
    desc: ?f"Gene set enrichment on genes differentially expressed and associated to DMRs"
    render-table:
      columns:

        pathway:
          link-to-url: 
            geneontology: 
              url: https://www.gsea-msigdb.org/gsea/msigdb/cards/{pathway}.html
        pval:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 2
        padj:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "#fdae6b"

        log2err:
          plot:
            heatmap:
              scale: linear
        ES:
          plot:
            heatmap:
              scale: linear
        NES:
          plot:
            heatmap:
              scale: linear
        size:
          plot:
            heatmap:
              scale: linear