__use_yte__: true

max-in-memory-rows: 5000

name: DMR regions
datasets:
  rna_annotations:
    path: ?input.rna_annotations
    separator: "\t"

default-view: rna_annotations
views:
  rna_annotations:
    dataset: rna_annotations
    desc: ?f"Differentially methylated regions (DMRs) between the experiments {params.base_experiment} and {wildcards.group2}. The DMRs were annotated with genomic elements using chipseeker (https://bioconductor.org/packages/release/bioc/vignettes/ChIPseeker/inst/doc/ChIPseeker.html ).\n
      The table is structured as follows; \n
      The chr, start_dmr, and end_dmr columns give the exact position of the DMR. The mean_methylation_difference column shows the difference in methylation between the two experiments. The annotation and transcriptID columns show genetic elements, while the absolute_signed_pi_val is the absolute value of the signed version of the pi-value score of the mean methylation difference (as proposed by Xiao et al. 2014 https://pubmed.ncbi.nlm.nih.gov/22321699/ ). \n
      The table is sorted in descending order by the absolute values of the signed versions of the pi-value score. Thus, values with small q-value but large methylation difference (and therefore values of importance) appear first."
    render-table:
      columns:
        PValue:
          label: pval_rna
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
              domain:
                - 0
                - 0.05
                - 0.25
        transcript_index:
          plot:
            heatmap:
              scale: linear
              range:
                - "#a1d99b"
                - "white"
                - "#fdae6b"
        mean_methylation_difference:
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -1
                - 0
                - 1 
        annotation_type:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: tableau20
        absolute_signed_pi_val:
          plot:
            heatmap:
              scale: linear
              range:
                - "white"
                - "#6baed6"