# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.
# Lese die sample.tsv-Datei ein und speichere die Daten in einer Liste von Tupeln
from snakemake.utils import min_version

min_version("8.13.0")


container: "docker://continuumio/miniconda3"


report: "report/workflow.rst"


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/dmr_heatmap.smk"
include: "rules/dmr_calling.smk"
include: "rules/prepare_meth_calling.smk"
include: "rules/prepare_enrichment.smk"
include: "rules/methylation_calling.smk"
include: "rules/annotate_dmrs.smk"


# declare https://github.com/Addimator/enrichment as a module
module enrichment:
    snakefile:
        # github(
        #     "Addimator/enrichment",
        #     path="workflow/Snakefile",
        #     # tag="v2.5.4",
        #     branch="main",
        # )
        "/homes/aprinz/enrichment/workflow/Snakefile"
    config:
        config


# use all rules from https://github.com/Addimator/enrichment
use rule * from enrichment


rule modified_all:
    default_target: True
    input:
        all_input,
        rules.all.input,
