# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.
# Lese die sample.tsv-Datei ein und speichere die Daten in einer Liste von Tupeln
from snakemake.utils import min_version

min_version("8.13.0")


container: "docker://continuumio/miniconda3"


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/dmr_heatmap.smk"
include: "rules/dmr_calling.smk"
include: "rules/get_data.smk"
include: "rules/methylation_calling.smk"


def read_sample_tsv(sample_tsv_path):
    samples = {}
    with open(sample_tsv_path, "r") as file:
        next(file)
        for line in file:
            name, path, sequencer = line.strip().split("\t")
            samples[name] = (path, sequencer)
    return samples


sample_tsv_path = config["sample_path"]
samples = read_sample_tsv(sample_tsv_path)


chromosome_conf = config["resources"]["ref"]


# declare https://github.com/Addimator/enrichment as a module
module enrichment:
    snakefile:
        github(
            "Addimator/enrichment",
            path="workflow/Snakefile",
            # tag="v2.5.4",
            branch="main",
        )
        # "/home/adrian/Documents/Promotion/locotact_stuff/enrichment/workflow/Snakefile"
    config:
        config


# use all rules from https://github.com/Addimator/enrichment
use rule * from enrichment


rule modified_all:
    default_target: True
    input:
        # rules.all.input,
        all_input,
