# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

from snakemake.utils import min_version

min_version("8.13.0")



container: "docker://continuumio/miniconda3"


report: "report/workflow.rst"


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/dmr_calling.smk"
include: "rules/methreg.smk"
# include: "rules/plots_paper.smk"
include: "rules/prepare_meth_calling.smk"
include: "rules/rna_seq.smk"
include: "rules/modkit.smk"
include: "rules/pbCpgTools.smk"
include: "rules/methylation_calling.smk"
include: "rules/compare_rna_jochen_excel.smk"
include: "rules/annotate_dmrs.smk"

inputflags:
    access.sequential


# declare https://github.com/Addimator/enrichment as a module
module enrichment:
    snakefile:
        # github(
        #     "Addimator/enrichment",
        #     path="workflow/Snakefile",
        #     # tag="v2.5.4",
        #     branch="main",
        # )
        "../../enrichment/workflow/Snakefile"
        # "/mnt/workspace/enrichment/workflow/Snakefile"
        # "/homes/aprinz/enrichment/workflow/Snakefile"
    config:
        # TODO: Give only enrichment specific config
        config
module kallisto_sleuth:
    snakefile:
        # github(
        #     "snakemake-workflows/rna-seq-kallisto-sleuth",
        #     path="workflow/Snakefile",
        #     # commit="59b9b6640872fd445d62245bdeccf9e80a97f868",
        #     branch="lr-kallisto"
        # )
        "../../rna-seq-kallisto-sleuth/workflow/Snakefile"
        # "/mnt/workspace/enrichment/workflow/Snakefile"
        # "/homes/aprinz/enrichment/workflow/Snakefile"
    config:
        config["kallisto_sleuth"]

# use all rules from https://github.com/Addimator/enrichment
# TODO the rulenames are the same as the ones from kallisto sleuth
# use rule * from enrichment
use rule * from kallisto_sleuth


rule modified_all:
    default_target: True
    input:
        all_input,
        rules.all.input,
